### PR TITLE
fix: Require content for submissions

### LINKED ISSUE #1852: Make Content Required for a New Submission
**Describe the bug**
After creating a new submission, a submitter can choose to submit the submission as Initially Submitted without adding content to it. 

**To Reproduce**
1. Go to the test publication's submission creation form (`/publication/1/create`)
2. Fill out the form and click the "Next" button
3. Click the "Submit for Review" button and confirm your choice in the modal dialog
4. Note the submission is submitted

**Expected behavior**
If content has not been associated with a submission draft, a user should not be able to submit it for review and change its status from "Draft" to "Initially Submitted". It should remain as a draft until then.

### PR DESCRIPTION
**Pull request by gmeben**
This prevents submissions without content from being submitted for review

Bonus:

* Improves the appearance of the radio button options on the Submission Content page.
* Fixes some framework-created title font-sizes appearing as less than 16px

Closes #1852

### CODE REVIEW

File: client/src/pages/SubmissionDraft.vue [hunk 1]
```diff
@@ -79,8 +79,9 @@
           <section class="q-mt-lg">
             <p>{{ $t(`submissions.create.submit.description`) }}</p>
             <q-btn
+              :disabled="draft.content.required.$invalid"
```
Comment (wreality) [inline client/src/pages/SubmissionDraft.vue:82]: image
Disabling the button appears to leave it in a undesirable state (see screenshot). Browser: Chrome

**Review by wreality — APPROVED** [review]
I think this looks good other than the problem with the disabled "Submit for review" button.

File: client/src/pages/SubmissionDraft.vue (hunk 1 above)
Comment (gmeben) [reply client/src/pages/SubmissionDraft.vue:82]: Good catch. I've been testing in dark mode this whole time and never noticed this.

Comment (gmeben) [reply client/src/pages/SubmissionDraft.vue]: This will now appear as expected. I also made the "Go" button the primary color to be consistent with the active call-to-action visual pattern throughout the application.
